export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
} as const

export const VALIDATION = {
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 200,
  SLUG_MIN_LENGTH: 2,
  SLUG_MAX_LENGTH: 200,
  ABBREVIATION_LENGTH: 2,
  TITLE_MIN_LENGTH: 5,
  TITLE_MAX_LENGTH: 300,
  DESCRIPTION_MIN_LENGTH: 10,
  DESCRIPTION_MAX_LENGTH: 5000,
  EXCERPT_MIN_LENGTH: 10,
  EXCERPT_MAX_LENGTH: 500,
  QUESTION_MIN_LENGTH: 5,
  QUESTION_MAX_LENGTH: 500,
  ANSWER_MIN_LENGTH: 5,
  ANSWER_MAX_LENGTH: 5000,
  COMPENSATION_MIN_LENGTH: 2,
  COMPENSATION_MAX_LENGTH: 200,
  URL_MAX_LENGTH: 2048,
  LOGO_MAX_LENGTH: 500,
  ELIGIBILITY_MAX_LENGTH: 1000,
  ICON_MIN_LENGTH: 2,
  ICON_MAX_LENGTH: 100,
  SEARCH_QUERY_MIN_LENGTH: 1,
  SEARCH_QUERY_MAX_LENGTH: 200,
} as const

export const SLUG_REGEX = /^[a-z0-9]+(?:-[a-z0-9]+)*$/

export const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

export const URL_REGEX = /^https?:\/\/.+/i

export const ALLOWED_IMAGE_FORMATS = ["image/jpeg", "image/png", "image/webp", "image/svg+xml"] as const

export const COMPENSATION = {
  MIN_HOURLY_RATE: 0,
  MAX_HOURLY_RATE: 10000,
  MIN_FIXED_AMOUNT: 0,
  MAX_FIXED_AMOUNT: 1000000,
} as const
